### ISSUE TITLE
nsrp_example.ipynb fails on rainfall_model.fit

### ISSUE THREAD

**Issue by MattHorritt** [rwgen1/rwgen#29]
Running on linux (Ubuntu 22.04.3) - which may be the issue as the guidance assumes windows. Will download the code and have a look at fixing. 

Output:
 ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[7], line 1
----> 1 rainfall_model.fit(
      2     n_workers=8,
      3     pdry_iterations=0, 
      4 )

File /merlin1/MISC/CPD/RWGen/rwgen-0.0.4/rwgen/rainfall/model.py:538, in RainfallModel.fit(self, fitting_method, parameter_bounds, fixed_parameters, n_workers, initial_parameters, smoothing_tolerance, output_filenames, fit_nsrp, fit_shuffling, random_seed, pdry_iterations, use_pooling)
    535 default_bounds.rename(columns={'index': 'parameter'}, inplace=True)
    537 # Identify parameters to fit (or not fit) and set parameter bounds
--> 538 parameters_to_fit, fixed_parameters, parameter_bounds = utils.define_parameter_bounds(
    539     parameter_bounds, fixed_parameters, self.parameter_names, default_bounds, self.unique_seasons
    540 )
    542 # Initial parameters are currently only relevant to empirical smoothing method
    543 if initial_parameters is not None:

File /merlin1/MISC/CPD/RWGen/rwgen-0.0.4/rwgen/rainfall/utils.py:1142, in define_parameter_bounds(parameter_bounds, fixed_parameters, required_parameters, default_bounds, unique_seasons)
   1140 # Reshape fixed parameters df so that it can be merged with bounds df
   1141 df1 = pd.melt(df1, id_vars='season', var_name='parameter', value_name='fixed_value')
-> 1142 df = pd.merge(df, df1, how='outer', on=['season', 'parameter'])
   1144 # Parameters to fit (and their bounds) need to be ordered for optimisation (more flexibility on fixed parameters)
   1145 fixed_parameters = {}  # key = tuple (season, parameter), values = parameter value

File ~/miniconda3/envs/rwgen/lib/python3.11/site-packages/pandas/core/reshape/merge.py:169, in merge(left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
    154     return _cross_merge(
    155         left_df,
    156         right_df,
   (...)
    166         copy=copy,
    167     )
    168 else:
--> 169     op = _MergeOperation(
    170         left_df,
    171         right_df,
    172         how=how,
    173         on=on,
    174         left_on=left_on,
    175         right_on=right_on,
    176         left_index=left_index,
    177         right_index=right_index,
    178         sort=sort,
    179         suffixes=suffixes,
    180         indicator=indicator,
    181         validate=validate,
    182     )
    183     return op.get_result(copy=copy)

File ~/miniconda3/envs/rwgen/lib/python3.11/site-packages/pandas/core/reshape/merge.py:804, in _MergeOperation.__init__(self, left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, indicator, validate)
    800 self._validate_tolerance(self.left_join_keys)
    802 # validate the merge keys dtypes. We may need to coerce
    803 # to avoid incompatible dtypes
--> 804 self._maybe_coerce_merge_keys()
    806 # If argument passed to validate,
    807 # check if columns specified as unique
    808 # are in fact unique.
    809 if validate is not None:

File ~/miniconda3/envs/rwgen/lib/python3.11/site-packages/pandas/core/reshape/merge.py:1479, in _MergeOperation._maybe_coerce_merge_keys(self)
   1473     # unless we are merging non-string-like with string-like
   1474     elif (
   1475         inferred_left in string_types and inferred_right not in string_types
   1476     ) or (
   1477         inferred_right in string_types and inferred_left not in string_types
   1478     ):
-> 1479         raise ValueError(msg)
   1481 # datetimelikes must match exactly
   1482 elif needs_i8_conversion(lk.dtype) and not needs_i8_conversion(rk.dtype):

ValueError: You are trying to merge on float64 and object columns for key 'parameter'. If you wish to proceed you should use pd.concat

**Comment by davidpritchard1** [comment]
Hi @MattHorritt, thanks very much for posting. You're right that the development and testing so far has focused on windows, which could be part of the issue here. I'll see if I can recreate this error on an Ubuntu system and post again with an update asap.

**Comment by MattHorritt** [comment]
I've fixed this (and another issue that cropped up along the way) - on my local branch iss29. Do you want me to push this to the repo for possible merge? Alternatively - I'm planning to go through the other examples so may find other issues - should we wait til I've done that?

**Comment by davidpritchard1** [comment]
Brilliant - thanks very much and well done! If you're thinking of going through the other examples then it might make sense to do that first as you say and then we can merge the changes all in one go.

**Comment by MattHorritt** [comment]
I've fixed a number of issues to get the 4x example scripts to run - mostly I think due to subtle changes in libraries. There were a couple of places where I had to change the _dayfirst_ keyword in pd.read_csv. 
I've got these on a new branch - if I can get write permission for the repo I'll push and you can have a look.

**Comment by MattHorritt** [comment]
I've pushed branch iss29 now. Have a look and merge (actually should just fast forward) as you see fit. I had some git issues so the commit history might look a bit odd, but should work OK. Am keeping on testing - one thing for me to look at is using 15 minute data from Defra hydrology explorer - am hacking it into 1 hr data for now.

**Comment by davidpritchard1** [comment]
Thanks very much for pushing the branch - I'll take a look at it early next week. (On the 15-minute data point, I'm working on some refactoring at the moment that will allow sub-hourly data into the process. This work should also make it easier to incorporate modifications into the underlying NSRP rainfall model that might help with performance at short durations. Happy to chat further about all of this at some point if useful!)
